version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend-container
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=True
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=notes_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend-container
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=/api
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: postgres-container
    environment:
      POSTGRES_DB: notes_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./backend/static:/app/static
      - ./backend/media:/app/media
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
